# Generated by Django 5.1 on 2024-09-20 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('Myapp', '0004_alter_order_created_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='price',
            field=models.DecimalField(decimal_places=2, default=20.0, max_digits=10),
        ),
        migrations.AddField(
            model_name='order',
            name='product_name',
            field=models.CharField(default='Achar', max_length=255),
        ),
        migrations.AddField(
            model_name='order',
            name='quantity',
            field=models.PositiveIntegerField(default=1),
        ),
        migrations.AddField(
            model_name='order',
            name='size',
            field=models.CharField(default='XL', max_length=10),
        ),
        migrations.DeleteModel(
            name='OrderItem',
        ),
    ]
